-- Seed local para busqueda de medicamentos en EC
-- Requerido por back/src/VitalFlow.His.Api/Infrastructure/Medicamento/PostgresMedicamentoRepository.cs

create schema if not exists sch_agenda;

create table if not exists sch_agenda.medicamento (
    id int generated by default as identity primary key,
    principio_activo varchar(200) not null,
    presentacion varchar(200) not null,
    producto varchar(300) not null,
    laboratorio varchar(200) not null,
    familia varchar(150) not null,
    forma varchar(120) not null,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_medicamento_principio_activo
    on sch_agenda.medicamento (principio_activo);

create index if not exists idx_medicamento_producto
    on sch_agenda.medicamento (producto);

create index if not exists idx_medicamento_laboratorio
    on sch_agenda.medicamento (laboratorio);

-- Carga minima para pruebas locales
insert into sch_agenda.medicamento (
    principio_activo, presentacion, producto, laboratorio, familia, forma
) values
    ('Paracetamol', '500 mg comprimidos x 20', 'Paracetamol 500', 'Genfar', 'Analgésicos', 'Comprimido'),
    ('Paracetamol', '1 g comprimidos x 10', 'Paracetamol 1 g', 'Bago', 'Analgésicos', 'Comprimido'),
    ('Ibuprofeno', '400 mg comprimidos x 20', 'Ibuprofeno 400', 'Bayer', 'AINE', 'Comprimido'),
    ('Amoxicilina', '500 mg cápsulas x 16', 'Amoxicilina 500', 'Gador', 'Antibióticos', 'Cápsula'),
    ('Omeprazol', '20 mg cápsulas x 30', 'Omeprazol 20', 'Roemmers', 'Gastroprotección', 'Cápsula')
on conflict do nothing;

-- Si tenes un CSV grande, usar COPY (ajustar ruta):
-- copy sch_agenda.medicamento (principio_activo, presentacion, producto, laboratorio, familia, forma)
-- from 'C:/ruta/medicamentos.csv'
-- with (format csv, header true, encoding 'UTF8');
